version: '3.8'
services:
  datatools-server:
    # Temporary! move back to "latest"
    build: ./
    ports:
      - "4000:4000"
    volumes:
      - type: bind
        source: ./configurations/docker/
        target: /config
      - type: bind
        source: ~/.aws
        target: /root/.aws
    depends_on:
      - mongo
      - postgres
  mongo:
    image: mongo
    restart: always
  postgres:
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    image: postgres
    restart: always